###
GET http://localhost:3000/menus

###
GET http://localhost:3000/menus/690a3f715597a08e374c2c35

###
GET http://localhost:3000/mesas/

###
GET http://localhost:3000/mesas/68ff86e7d56a1efc82d13d23

###
GET http://localhost:3000/comandas/